image: ros:melodic-perception

cache:
  paths:
    - ccache/

before_script:
  - git clone https://gitlab.com/VictorLamoine/ros_gitlab_ci.git
  - source ros_gitlab_ci/gitlab-ci.bash >/dev/null
  - apt install -y libceres1 libceres-dev

catkin_tools:
  stage: build
  script:
    - catkin build --summarize --no-status --force-color
