name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: ros-tooling/setup-ros@0.0.18
    # Run the generator and output the results to a file
    - run: |
        rosinstall_generator camera_model --rosdistro melodic \
        --deps-only --deps --upstream-development > /tmp/deps.repos
    - uses: ros-tooling/action-ros-ci@0.0.15
      with:
        package-name: camera_model
        vcs-repo-file-url: /tmp/deps.repos
